import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tabangan App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className='flex justify-between items-center p-10'>
          <h1 className='font-bold'>{metadata.title}</h1>
          <nav>
            <ul className='flex gap-10 uppercase '>
              <li>
                <Link href='/'>Home</Link>
              </li>
              <li>
                <Link href='/projects'>Projects</Link>
              </li>
              <li>
                <Link href='/products'>Products</Link>
              </li>
            </ul>
          </nav>
        </div>
        {children}
      </body>
    </html>
  )
}
